### ISSUE TITLE
Composer not installing on the project

### ISSUE THREAD

**Issue by Dynamics567** [Masud99Rana/Online-News-Portal-Laravel#1]
in my attempt of installing composer in the project directory. pls help

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'blog.settings' doesn't exist

**Comment by Masud99Rana** [comment]
Hi,
In this project, I have passes some global variables to all views.
You have to comment/remove them before the composer install.
After successfully composer install, you have to keep them as before ( Like now ).
I will update the readme file soon.

Follow below steps:

Step: 01 comment/remove global variables,
Goto app =>Providers => AppServiceProvider.php
Make public function boot() method as like below
-----------------
    public function boot()
    {
        Schema::defaultStringLength(191);
    }
---------------

Step: 02 install composer

Step: 03 Add all global variables that you have removed in step 01
Make sure AppServiceProvider.php looks like below:
https://github.com/Masud99Rana/Online-News-Portal-Laravel/blob/master/app/Providers/AppServiceProvider.php

Note: This project is not production-ready. I just practice Laravel in it.

Feel free to knock me if you have any queries.
https://www.facebook.com/MasudRana99MR
